### ISSUE TITLE
reporter option for "debug" is not implemented

### ISSUE THREAD

**Issue by oscarcenteno** [reportportal/agent-js-mocha#100]
I would like to able to turn off the logging for all the API calls so my console looks cleaner while running the tests.

After looking at the code, and tests, I notice it is not yet implemented. Can you please confirm or correct me?

**Comment by AmsterGet** [comment]
Hello @oscarcenteno !
If I understand you correctly, you are talking about the [debug option](https://github.com/reportportal/agent-js-mocha#:~:text=Investigate%27%20on%20application.-,debug,-Optional), which is intended to display client-javascript debug logs.
Since this is a configuration option propagated through the JS client, its logic is [there](https://github.com/reportportal/client-javascript/blob/develop/lib/report-portal-client.js#L35) and is applied as soon as the client instance is [created](https://github.com/reportportal/agent-js-mocha/blob/develop/lib/mochaReporter.js#L48).

So this option defaults to `false` and requires no additional action if you don't want to see debug logs from the client lib.

Hope this helped!
